### ISSUE TITLE
Vistas

### ISSUE THREAD

**Issue by miguelvilla** [Arquisoft/Agents_e5a#4]
Añadir las vistas de los nuevos módulos descritos en el documento de entrega

**Comment by JesusFVelasco** [comment]
Añadida nueva vista del InciDasboard, faltando Interfaces, Comportamiento y Justificación de las decisiones

**Comment by JesusFVelasco** [comment]
Actualizada la vista del contexto con los nuevos modulos

**Comment by JesusFVelasco** [comment]
Actualizada la vista de Agents

**Comment by guillediaz11** [comment]
solucionado interfaces y comportamiento con @camporrox97

**Comment by camporrox97** [comment]
refinamiento de vistas con @guillediaz11
