### ISSUE TITLE
Actualizar información sobre el nuevo módulo

### ISSUE THREAD

**Issue by miguelvilla** [Arquisoft/Agents_e5a#6]

**Comment by JesusFVelasco** [comment]
Añadido el nuevo modulo a los requisitos y un nuevo Stakeholder (personal de gestion de incidencias)

**Comment by miguelvilla** [comment]
Ampliación en el apartado de la introducción realizada

**Comment by JesusFVelasco** [comment]
Corregidos errores de la documentación como nombres, códigos de los atributos, stakeholders, etc.

**Comment by camporrox97** [comment]
Completada la actualización con @guillediaz11
